# Generated by Django 3.0 on 2023-07-31 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfimg',
            field=models.ImageField(default='pfle.png', upload_to='Profiles/'),
        ),
        migrations.CreateModel(
            name='TchProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tchdesg', models.CharField(max_length=20)),
                ('tchexpr', models.IntegerField()),
                ('tchsubject', models.CharField(max_length=50)),
                ('tchbrnch', models.CharField(max_length=50)),
                ('tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbranch', models.CharField(max_length=50)),
                ('syear', models.CharField(max_length=50)),
                ('sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(choices=[('s', 'Select your Leave Type'), ('Personal', 'Personal'), ('Medical', 'Medical')], default='s', max_length=15)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('apldate', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=200)),
                ('leavestatus', models.CharField(choices=[('g', 'Pending'), ('a', 'Approved'), ('d', 'Declined')], default='g', max_length=10)),
                ('tchdescc', models.CharField(max_length=200)),
                ('leaatch', models.FileField(upload_to='Attachments/')),
                ('st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
