# Generated by Django 3.0 on 2023-08-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LApp', '0004_auto_20230801_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='apldate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(),
        ),
    ]
