class Calsi:
    def add(n1,n2):
        return n1+n2
    def sub(n1,n2):
        return n1-n2
class Math:
    def power(bval,exval):
        return bval**exval
    def isEven(v):
        if v%2==0:
            return True
        return False
def isOdd(v):
    if v%2!=0:
        return True
    return False